export const TODOS_ADDED= "TODOS_ADDED";
export const TODOS_ADDED_SUCCESS="TODOS_ADDED_SUCCESS";
export const TODOS_DELETED="TODOS_DELETED";
export const TODOS_DELETED_SUCCESS="TODOS_DELETED_SUCCESS";