export const ADD_TO_CART="ADD_TO_CART";
export const CHECK_OUT_REQUEST="CHECK_OUT_REQUEST";
export const CHECK_OUT_SUCCESS="CHECK_OUT_SUCCESS";
export const CHECK_OUT_FAILURE="CHECK_OUT_FAILURE";
export const RECEIVE_PRODUCTS="RECEIVE_PRODUCTS";